version: '3.9' # Kommentit, t채ss채 docker versio
services:
  php-env:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./src:/var/www/html
    ports:
      - 1000:80 # T채ll채 osoitteella otetaan yhteys selaimella
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.3 # latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 1001:80
    environment:
      PMA_ARBITRARY: 1  
    depends_on:
      - mysql_db